/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    FormSection: typeof import('./src/components/FormSection.vue')['default']
    ResultSection: typeof import('./src/components/ResultSection.vue')['default']
    RiskGauge: typeof import('./src/components/RiskGauge.vue')['default']
  }
}
